In [173]:
import pandas as pd
import json

df = pd.read_csv('yelp.csv')

df.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."

In [174]:
# summary statistics
summary_stats = df.describe()

summary_stats

,latitude,longitude,stars,review_count,is_open
count,150346.000000,150346.000000,150346.000000,150346.000000,150346.00000
mean,36.671150,-89.357339,3.596724,44.866561,0.79615
std,5.872759,14.918502,0.974421,121.120136,0.40286
min,27.555127,-120.095137,1.000000,5.000000,0.00000
25%,32.187293,-90.357810,3.000000,8.000000,1.00000
50%,38.777413,-86.121179,3.500000,15.000000,1.00000
75%,39.954036,-75.421542,4.500000,37.000000,1.00000
max,53.679197,-73.200457,5.000000,7568.000000,1.00000

In [175]:
# evaluating null values
null_counts = df.isnull().sum()

null_columns = null_counts[null_counts > 0]
print(null_columns)

address         5127
postal_code       73
attributes     13744
categories       103
hours          23223
dtype: int64

In [176]:
# datatypes
df.dtypes

business_id      object
name             object
address          object
city             object
state            object
postal_code      object
latitude        float64
longitude       float64
stars           float64
review_count      int64
is_open           int64
attributes       object
categories       object
hours            object
dtype: object

In [177]:
# inspecting various attribute types
import ast

df['attributes'] = df['attributes'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

unique_keys = set()
for row in df['attributes'].dropna():
    if isinstance(row, dict):
        unique_keys.update(row.keys())

print(unique_keys)

{'NoiseLevel', 'GoodForMeal', 'WheelchairAccessible', 'RestaurantsReservations', 'BikeParking', 'Ambience', 'WiFi', 'AgesAllowed', 'RestaurantsPriceRange2', 'HasTV', 'ByAppointmentOnly', 'HappyHour', 'DietaryRestrictions', 'Alcohol', 'DriveThru', 'CoatCheck', 'BusinessAcceptsBitcoin', 'RestaurantsTableService', 'RestaurantsDelivery', 'BusinessAcceptsCreditCards', 'AcceptsInsurance', 'RestaurantsCounterService', 'RestaurantsTakeOut', 'BestNights', 'BusinessParking', 'Music', 'Smoking', 'Caters', 'RestaurantsAttire', 'OutdoorSeating', 'GoodForDancing', 'Corkage', 'HairSpecializesIn', 'GoodForKids', 'Open24Hours', 'BYOB', 'DogsAllowed', 'BYOBCorkage', 'RestaurantsGoodForGroups'}

In [178]:
# 
all_categories = set()
df['categories'].dropna().apply(lambda x: all_categories.update(x.split(', ')))
print(all_categories)

{'Traffic Schools', 'Senegalese', 'Shared Office Spaces', 'Internet Cafes', 'Archery', 'Hair Loss Centers', 'Shades & Blinds', 'Live/Raw Food', 'Paragliding', 'Electricity Suppliers', 'Dance Clubs', 'Fireworks', 'Public Relations', 'RV Dealers', 'Tree Services', 'Cooking Schools', 'Pop-up Shops', 'Colombian', 'Auto Parts & Supplies', 'Patent Law', 'Anesthesiologists', 'Cuban', 'Tanning', 'Carpet Installation', 'Cucina campana', 'Libraries', 'Marketing', 'Livestock Feed & Supply', 'Structural Engineers', 'Playgrounds', 'Medical Centers', 'Proctologists', 'Cocktail Bars', 'Whale Watching Tours', 'Car Dealers', 'Clothing Rental', 'Peruvian', 'Tiki Bars', 'Shredding Services', 'Circuit Training Gyms', 'Israeli', 'Estate Liquidation', 'ATV Rentals/Tours', 'Concierge Medicine', 'Kiosk', 'Wine Tours', 'Pediatric Dentists', 'Health Markets', 'Mobile Phone Repair', 'Juice Bars & Smoothies', 'Champagne Bars', 'Haitian', 'Elder Care Planning', 'Handyman', 'Chiropractors', 'Baseball Fields', 'Wedding Planning', 'Wholesalers', 'Courthouses', 'Jewelry Repair', 'Scooter Rentals', 'Piercing', 'Paddleboarding', 'Dog Walkers', 'Farms', 'Specialty Food', 'Party Bus Rentals', 'Child Care & Day Care', 'Pop-Up Restaurants', 'Holiday Decorating Services', 'Appliances & Repair', 'Museums', 'Financial Advising', 'Seafood Markets', 'Bridal', 'Pool & Billiards', 'Beverage Store', 'Gold Buyers', 'Public Markets', 'Horse Racing', 'Officiants', 'CSA', 'Town Car Service', 'Spray Tanning', 'Caterers', 'Ophthalmologists', 'Tai Chi', 'Soccer', 'Gun/Rifle Ranges', 'Guest Houses', 'IP & Internet Law', 'Private Schools', "Men's Hair Salons", 'Masonry/Concrete', 'Portable Toilet Services', 'Sports Wear', 'Drugstores', 'Carpet Dyeing', 'Coffeeshops', 'Trailer Rental', 'Custom Cakes', 'Shutters', 'Chicken Wings', 'Optometrists', 'Laser Tag', 'Eyelash Service', 'Stadiums & Arenas', 'Metal Fabricators', 'Art Museums', 'Cryotherapy', 'Urgent Care', 'Polish', 'Pet Groomers', 'Tacos', 'Art Installation', 'Real Estate Photography', 'Herbal Shops', 'Workers Compensation Law', 'Creperies', 'Sicilian', 'Party Equipment Rentals', 'Tasting Classes', 'Grocery', 'Holistic Animal Care', 'Arts & Crafts', 'Military Surplus', 'Behavior Analysts', 'Tubing', 'Immigration Law', 'Family Practice', 'Professional Services', 'Packing Supplies', 'Cideries', 'Street Vendors', 'Translation Services', 'Pressure Washers', 'Hybrid Car Repair', 'Lounges', 'Zoos', 'Fitness & Instruction', 'Patisserie/Cake Shop', 'Data Recovery', 'Asian Fusion', 'Laser Hair Removal', 'DJs', 'Home Inspectors', 'Oxygen Bars', 'Sports Psychologists', 'Vehicle Wraps', 'Walking Tours', 'Szechuan', 'Windshield Installation & Repair', 'Parks', 'Powder Coating', 'Cremation Services', 'Tapas Bars', 'Auto Insurance', 'Body Contouring', 'Solar Panel Cleaning', 'Party Characters', 'Bird Shops', 'Homeless Shelters', 'International Grocery', 'Bail Bondsmen', 'Singaporean', 'Wine & Spirits', 'Gerontologists', 'Bingo Halls', 'Musical Instruments & Teachers', 'Propane', 'Foot Care', 'Dietitians', 'Criminal Defense Law', 'Chocolatiers & Shops', 'Hot Tub & Pool', 'New Mexican Cuisine', 'Auto Glass Services', 'Sport Equipment Hire', 'Legal Services', 'Pathologists', 'Tours', 'Bike Rentals', 'Mortuary Services', 'Home Decor', 'Gymnastics', 'Bocce Ball', 'Grilling Equipment', 'Laotian', 'Boat Repair', 'Mags', 'Hotels', 'Financial Services', 'Rafting/Kayaking', 'Motorcycle Dealers', 'Animal Assisted Therapy', 'Home Automation', 'Car Share Services', 'Photographers', 'Makeup Artists', 'Cheesesteaks', 'Payroll Services', 'Pilates', 'Talent Agencies', 'Community Service/Non-Profit', 'Photography Stores & Services', 'Security Systems', 'Balloon Services', 'Airsoft', 'Ethical Grocery', 'Editorial Services', 'Rodeo', 'Awnings', 'Travel Services', 'Syrian', 'Electronics Repair', 'Kebab', 'Badminton', 'Piano Services', 'Biohazard Cleanup', 'Pakistani', 'Beer Tours', 'Bike tours', 'Nanny Services', 'Snow Removal', 'Driving Schools', 'Adult Education', 'Hepatologists', 'Shoe Repair', 'Jazz & Blues', 'Bike Shop', 'Water Stores', 'Floral Designers', 'Auto Detailing', 'Mountain Biking', 'Advertising', 'IT Services & Computer Repair', 'College Counseling', 'Internet Service Providers', 'Martial Arts', 'Art Schools', 'Smokehouse', 'Lighting Fixtures & Equipment', 'Shipping Centers', 'International', 'Post Offices', 'Pets', 'Snorkeling', 'Disc Golf', 'Commissioned Artists', 'Mosques', 'Trailer Dealers', 'Sri Lankan', 'Community Gardens', 'Buses', 'Religious Organizations', 'Pet Hospice', 'Pool Cleaners', 'Henna Artists', 'Check Cashing/Pay-day Loans', 'Hydro-jetting', 'Beer Hall', 'Appraisal Services', 'Food Delivery Services', 'Real Estate Agents', 'Outdoor Gear', 'Police Departments', 'Belgian', 'Matchmakers', 'Hobby Shops', 'Education', 'Auction Houses', 'Persian/Iranian', 'Breakfast & Brunch', 'Nurseries & Gardening', 'Poutineries', 'Bike Parking', 'Personal Care Services', 'Pharmacy', 'Estate Planning Law', 'Herbs & Spices', 'Rock Climbing', "Men's Clothing", 'Trivia Hosts', 'Water Delivery', 'Beach Bars', 'Bike Repair', 'Czech', 'Prosthodontists', 'Fireplace Services', 'Event Planning & Services', 'Farm Equipment Repair', 'Public Art', 'Bistros', 'Vascular Medicine', 'Gutter Services', 'Yoga', 'Wineries', 'Convenience Stores', 'Scavenger Hunts', 'Bicycle Paths', 'Mobile Phones', 'Barre Classes', 'Environmental Testing', 'Prosthetics', 'Synagogues', 'Painters', 'Vinyl Records', 'Aircraft Dealers', 'Waxing', 'Strip Clubs', 'Roof Inspectors', 'Telecommunications', 'Lactation Services', 'Midwives', 'Valet Services', 'Modern European', 'Planetarium', 'Luggage Storage', 'Vacation Rentals', 'Gyms', 'Storefront Clinics', 'Window Washing', 'Cardio Classes', 'Neurologist', 'Venues & Event Spaces', 'Bars', 'Guamanian', 'Trinidadian', 'Ethnic Food', 'Acne Treatment', 'Newspapers & Magazines', 'Furniture Reupholstery', 'Opera & Ballet', 'Auto Upholstery', 'Cosmetic Dentists', 'Axe Throwing', 'Sex Therapists', 'Paint & Sip', 'Childproofing', 'Gift Shops', 'Podiatrists', 'Pet Training', 'Meaderies', 'Water Suppliers', 'Hats', 'Blood & Plasma Donation Centers', 'Tanning Beds', 'Ukrainian', 'Estheticians', 'Pretzels', 'Costumes', 'Software Development', 'Physical Therapy', 'Nephrologists', 'Hotel bar', 'Fish & Chips', 'Ferries', 'Taiwanese', 'Falafel', 'Towing', 'Firewood', 'Doctors', 'Airlines', 'Tobacco Shops', 'Chinese', 'Aquariums', 'Siding', 'Car Stereo Installation', 'Bar Crawl', 'Hair Salons', 'Dry Cleaning & Laundry', 'Campgrounds', '& Probates', 'Cheese Tasting Classes', 'Teeth Whitening', 'Tennis', 'Candle Stores', 'Digitizing Services', 'Marinas', 'Tableware', 'Plumbing', 'Swimming Lessons/Schools', 'Local Fish Stores', 'Barbeque', 'Medical Supplies', 'German', 'Bagels', 'Home Window Tinting', 'Lingerie', 'Maternity Wear', 'Radiologists', 'Knife Sharpening', 'Dialysis Clinics', 'Backflow Services', 'Carpet Cleaning', 'Historical Tours', 'Austrian', 'Summer Camps', 'Sports Clubs', 'Private Jet Charter', 'Garage Door Services', 'Personal Injury Law', 'Lebanese', 'Process Servers', 'Malaysian', 'Grout Services', 'Country Clubs', 'Basque', 'Electricians', 'American (New)', 'Home Health Care', 'Ethnic Grocery', 'Surf Schools', 'Shoe Stores', 'Tires', 'Canadian (New)', 'Home Theatre Installation', 'Sports Bars', 'Language Schools', 'Pet Services', 'Aircraft Repairs', 'Veterans Organizations', 'Oriental', 'Pain Management', 'Race Tracks', 'Ultrasound Imaging Centers', 'Metal Detector Services', 'Themed Cafes', 'Art Restoration', 'Massage', 'Screen Printing', 'Ski & Snowboard Shops', 'Astrologers', 'Hockey Equipment', 'Psychologists', 'Hardware Stores', 'Baby Gear & Furniture', 'Windows Installation', 'Spine Surgeons', 'Donuts', 'RV Repair', 'Qi Gong', 'Mortgage Brokers', 'Go Karts', 'Playsets', 'Formal Wear', 'Solar Installation', 'Dance Studios', 'Artificial Turf', 'Office Equipment', 'Festivals', 'Chicken Shop', 'DUI Schools', 'Kosher', 'Reptile Shops', 'Car Window Tinting', 'Christmas Trees', 'Wallpapering', 'Currency Exchange', 'Skiing', 'Dog Parks', 'Flowers', 'Shaved Ice', 'Teppanyaki', 'Restaurant Supplies', 'Bubble Tea', 'Souvenir Shops', 'Accountants', 'Races & Competitions', 'Challenge Courses', 'Aquarium Services', 'Lighting Stores', 'Psychics', 'Hospice', 'Sledding', 'Pet Photography', 'Ceremonial Clothing', 'Amateur Sports Teams', 'Permanent Makeup', 'Italian', 'Amusement Parks', 'Crane Services', 'Pulmonologist', 'Japanese Curry', 'Drones', 'Kiteboarding', 'Aestheticians', 'Pet Sitting', 'Parenting Classes', 'Arcades', 'Waldorf Schools', 'Donburi', 'Air Duct Cleaning', 'Taxidermy', 'Diamond Buyers', 'Ayurveda', 'Nail Technicians', 'Horse Boarding', 'Laundromat', 'Brazilian Jiu-jitsu', 'Insulation Installation', 'Landmarks & Historical Buildings', 'Scuba Diving', 'Hearing Aid Providers', 'Batting Cages', 'Sewing & Alterations', 'Australian', 'Cheerleading', 'Furniture Rental', 'Sports Medicine', 'Swimwear', 'Breweries', 'Traditional Clothing', 'Salad', 'Flooring', 'Art Consultants', 'Rest Stops', 'Wildlife Hunting Ranges', 'Beaches', 'Trains', 'Hainan', 'Dumpster Rental', 'Car Brokers', 'Tiling', 'Town Hall', 'Spiritual Shop', 'Lakes', 'Elevator Services', 'Auto Loan Providers', 'Retirement Homes', 'Golf Equipment Shops', 'Notaries', 'Social Security Law', 'Makerspaces', 'Hair Stylists', 'Sheds & Outdoor Storage', 'Arabic', 'Drive-Thru Bars', 'Adult', 'Hawaiian', 'Fishing', 'Orthodontists', 'Comedy Clubs', 'Cantonese', 'Recreation Centers', 'Condominiums', 'Dry Cleaning', 'Iberian', 'Professional Sports Teams', 'Petting Zoos', 'Pasta Shops', 'Memory Care', 'African', 'Sauna Installation & Repair', 'Environmental Abatement', 'General Festivals', 'Barbers', 'Eastern European', 'Signmaking', 'Psychic Mediums', 'Arts & Entertainment', 'Carousels', 'Paint-Your-Own Pottery', 'Infectious Disease Specialists', 'Banks & Credit Unions', 'Fuzhou', 'Vegetarian', 'Hungarian', 'Macarons', 'Water Purification Services', 'Conveyor Belt Sushi', 'Wills', 'Scandinavian', 'Life Insurance', 'Safe Stores', 'Plastic Surgeons', 'Holiday Decorations', 'Animal Shelters', 'Greek', 'Florists', 'RV Rental', 'Hunting & Fishing Supplies', 'Bounce House Rentals', 'Piano Stores', 'Limos', 'Musicians', 'Attraction Farms', 'Nail Salons', 'Beach Equipment Rentals', 'Vitamins & Supplements', 'Pet Waste Removal', 'Hair Removal', 'Social Clubs', 'Preventive Medicine', 'Sunglasses', 'Party Supplies', 'Visitor Centers', 'Piano Bars', 'Periodontists', 'Public Adjusters', 'Music & DVDs', 'Middle Schools & High Schools', 'Embassy', 'Heating & Air Conditioning/HVAC', 'Office Cleaning', 'Props', 'Dim Sum', 'Halfway Houses', 'Dance Wear', 'Nursing Schools', 'Boxing', 'Bus Tours', 'Bike Sharing', 'Apartments', 'Bubble Soccer', 'Assisted Living Facilities', 'Lice Services', 'Outdoor Movies', 'Indoor Playcentre', 'Movers', 'Patio Coverings', 'Airport Lounges', 'Rolfing', 'Framing', 'Desserts', 'Audiologist', 'Animal Physical Therapy', 'CPR Classes', 'Cafes', 'Soup', 'Home Staging', 'Trainers', 'Dermatologists', 'Swimming Pools', 'Cooking Classes', 'Commercial Real Estate', 'Lahmacun', 'Plus Size Fashion', 'Halotherapy', 'Auto Repair', 'Business Consulting', 'Threading Services', 'Business Law', 'Videographers', 'Mass Media', 'Computers', 'Phlebologists', 'Dentists', 'Gastropubs', 'Recycling Center', 'Graphic Design', 'Vintage & Consignment', 'Allergists', 'Dart Arenas', 'Hotels & Travel', 'Racing Experience', 'Climbing', 'Colonics', 'Contract Law', 'Interior Design', 'Leather Goods', 'Tax Law', 'Tex-Mex', 'Hospitalists', 'Wholesale Stores', 'Diagnostic Imaging', 'Mediators', 'Local Services', 'Uniforms', 'Golf Equipment', 'Debt Relief Services', 'Hydroponics', 'Health Insurance Offices', 'Spin Classes', 'Surfing', 'Hostels', 'Laundry Services', 'Osteopaths', 'Endocrinologists', 'Serbo Croatian', 'Brasseries', 'Couriers & Delivery Services', 'Preschools', 'Tenant and Eviction Law', 'Cupcakes', 'Commercial Truck Dealers', 'Organic Stores', 'Silent Disco', 'Bangladeshi', 'Free Diving', 'Striptease Dancers', 'Toy Stores', 'Cannabis Collective', 'Obstetricians & Gynecologists', 'Acai Bowls', 'Halal', 'Food Tours', 'Mobile Phone Accessories', 'Beauty & Spas', 'Chinese Martial Arts', 'Kitchen Supplies', 'Cosmetology Schools', 'Pita', 'Glass Blowing', 'Active Life', 'Meat Shops', 'Septic Services', 'Food Trucks', 'Real Estate', 'Furniture Repair', 'Billing Services', 'Vietnamese', 'Self Storage', 'Portuguese', 'Carpeting', 'Fire Departments', 'Medical Spas', 'Gluten-Free', 'Vegan', 'Parasailing', 'Public Services & Government', 'Osteopathic Physicians', 'Pawn Shops', 'Parklets', 'Bartending Schools', 'Psychiatrists', 'Furniture Assembly', 'Middle Eastern', 'Latin American', 'Fire Protection Services', 'Concept Shops', 'Cinema', 'Passport & Visa Services', 'Adult Entertainment', 'General Litigation', 'Bespoke Clothing', 'Video Game Stores', 'Utilities', 'Homeowner Association', 'Trade Fairs', 'Spanish', 'Saunas', 'Olive Oil', 'Mobile Dent Repair', 'Home Developers', 'Truck Rental', 'Day Camps', 'Indonesian', 'Decks & Railing', 'Mexican', 'Self-defense Classes', 'High Fidelity Audio Equipment', 'Comic Books', 'Boudoir Photography', 'Diners', 'Beer Bar', 'Machine Shops', 'Shopping Centers', 'Car Inspectors', 'British', 'Mongolian', 'Laser Eye Surgery/Lasik', 'Hakka', 'Karaoke', 'Used Bookstore', 'Cabaret', 'Installment Loans', 'Hospitals', 'Fabric Stores', 'Eyebrow Services', 'American (Traditional)', 'Home Network Installation', 'Vocal Coach', 'Photography Classes', 'Waffles', "Children's Clothing", 'Roofing', 'Home Energy Auditors', 'Indoor Landscaping', 'Sleep Specialists', 'Trusts', 'First Aid Classes', 'Boat Tours', 'Candy Stores', 'Mobility Equipment Sales & Services', 'Golf', 'Russian', 'Tuscan', 'Private Tutors', 'Hypnosis/Hypnotherapy', 'Luggage', 'Audio/Visual Equipment Rental', 'Junkyards', 'Skilled Nursing', 'Supernatural Readings', 'Montessori Schools', 'Fast Food', 'Special Education', 'Web Design', 'Carpenters', 'Transmission Repair', 'Donation Center', 'Surf Shop', 'Jails & Prisons', 'Wine Bars', 'Karate', 'Ice Delivery', 'Gunsmith', 'Ramen', 'Drywall Installation & Repair', 'Ziplining', 'Pan Asian', 'Jet Skis', 'Insurance', 'Wraps', 'Team Building Activities', 'Food Banks', 'Interlock Systems', 'Club Crawl', 'Adoption Services', 'Karaoke Rental', 'Tui Na', 'Otologists', 'Smog Check Stations', 'Hong Kong Style Cafe', 'Delicatessen', 'Bus Rental', 'Shopping', 'Nudist', 'Kids Activities', 'Wigs', 'Books', 'Neurotologists', 'Salvadoran', 'Calligraphy', 'Tabletop Games', 'Caribbean', 'Mortgage Lenders', 'Cards & Stationery', 'Speech Therapists', 'Rugs', 'Scooter Tours', 'Do-It-Yourself Food', 'Addiction Medicine', 'Sardinian', 'Burgers', 'Furniture Stores', 'Fencing Clubs', 'Taxis', 'Guns & Ammo', 'Home Cleaning', 'Traffic Ticketing Law', 'Personal Chefs', 'RV Parks', 'Oncologist', 'Burmese', 'Bartenders', 'Ranches', 'Wedding Chapels', 'Keys & Locksmiths', 'Fertility', 'Aviation Services', 'Food Court', 'Refinishing Services', 'Pet Boarding', 'Demolition Services', 'Gelato', 'Consumer Law', 'Party & Event Planning', 'Building Supplies', 'Orthopedists', 'Irish', 'Home Services', 'Veterinarians', 'Land Surveying', 'Escape Games', 'Food', 'Cigar Bars', 'Perfume', 'Emergency Pet Hospital', 'Junk Removal & Hauling', 'Poke', 'Grill Services', 'Pool Halls', 'Ski Schools', 'Landscaping', 'Egyptian', 'Ear Nose & Throat', 'Home Organization', 'Trophy Shops', 'Personal Assistants', 'Roadside Assistance', 'Fences & Gates', 'Immunodermatologists', 'Event Photography', 'Natural Gas Suppliers', 'Music Venues', 'Gastroenterologist', 'Bicycles', 'Virtual Reality Centers', 'Korean', 'Ticket Sales', 'Used', 'Gemstones & Minerals', 'Cultural Center', 'Face Painting', 'Landscape Architects', 'Kitchen Incubators', 'Boat Dealers', 'Career Counseling', 'Watches', 'Boat Parts & Supplies', 'Retina Specialists', 'Steakhouses', 'Housing Cooperatives', 'Television Stations', 'Motorcycle Repair', 'Screen Printing/T-Shirt Printing', 'DIY Auto Shop', 'Bed & Breakfast', 'Irrigation', 'Countertop Installation', 'Cafeteria', 'Filipino', 'Health & Medical', 'Door Sales/Installation', 'Head Shops', 'Casinos', 'Session Photography', 'Wildlife Control', 'Pumpkin Patches', 'Wine Tasting Classes', 'Bookkeepers', 'Outdoor Power Equipment Services', 'Real Estate Law', 'Music & Video', 'Sailing', 'Health Coach', 'Religious Items', 'Comfort Food', 'Coffee & Tea', 'Vehicle Shipping', 'Oil Change Stations', 'Engraving', 'Cannabis Tours', 'Departments of Motor Vehicles', 'Bus Stations', 'Personal Shopping', 'Skin Care', 'Battery Stores', 'Donairs', 'Endodontists', 'Discount Store', 'Shoe Shine', 'Stucco Services', 'Fingerprinting', 'Divorce & Family Law', 'Experiences', 'Irish Pub', 'Japanese', 'Religious Schools', 'Fuel Docks', 'Employment Law', 'Commercial Truck Repair', 'Water Heater Installation/Repair', 'Kids Hair Salons', 'Duplication Services', 'Day Spas', 'EV Charging Stations', 'Hookah Bars', 'Airports', 'Specialty Schools', 'Distilleries', 'Print Media', 'Roman', 'Puerto Rican', 'Apartment Agents', 'Accessories', 'Weight Loss Centers', 'Mobile Home Parks', 'Packing Services', 'Reiki', 'Delis', 'Reflexology', 'Drama Schools', 'Waterproofing', 'DUI Law', 'Eyewear & Opticians', 'Butcher', 'Ice Cream & Frozen Yogurt', 'Beer', 'Car Auctions', 'Meditation Centers', 'Thrift Stores', 'Guitar Stores', 'Party Bike Rentals', 'Musical Instrument Services', 'Orthotics', 'Kickboxing', 'Tapas/Small Plates', 'Life Coach', 'Music Production Services', 'Pole Dancing Classes', 'Pet Insurance', 'Cheese Shops', 'Mailbox Centers', 'Imported Food', 'Tea Rooms', 'Product Design', 'Cycling Classes', 'Muay Thai', 'Popcorn Shops', 'Nicaraguan', 'Oral Surgeons', 'Eatertainment', 'Firearm Training', 'Alternative Medicine', 'Childbirth Education', 'Tutoring Centers', 'Medical Cannabis Referrals', 'Flowers & Gifts', 'Kitchen & Bath', 'Dive Shops', 'Pet Breeders', 'Water Parks', 'Reproductive Health Services', 'Recording & Rehearsal Studios', 'Venezuelan', 'Knitting Supplies', 'Surgeons', 'Circus Schools', 'Travel Agents', 'Shaved Snow', 'Fur Clothing', 'Neuropathologists', 'Ethiopian', 'Flight Instruction', 'Prenatal/Perinatal Care', 'Excavation Services', 'Community Centers', 'Basketball Courts', 'Investing', 'Service Stations', 'Hair Extensions', 'Nutritionists', 'Pediatricians', 'Himalayan/Nepalese', 'Vape Shops', 'Cosmetic Surgeons', 'Seafood', 'Somali', 'Pick Your Own Farms', 'Jewelry', 'Customized Merchandise', 'Cabinetry', 'Bankruptcy Law', 'Fitness/Exercise Equipment', 'Architectural Tours', 'Honey', 'Cajun/Creole', 'Farmers Market', 'Tattoo', 'Counseling & Mental Health', 'Speakeasies', 'Taekwondo', 'Skydiving', 'Vocational & Technical School', 'Chimney Sweeps', 'Pedicabs', 'Laboratory Testing', 'Cambodian', 'Skating Rinks', 'Restaurants', 'Crisis Pregnancy Centers', 'Educational Services', 'Security Services', 'Golf Cart Rentals', 'Mini Golf', 'Private Investigation', 'Gay Bars', 'Photo Booth Rentals', 'Hot Air Balloons', 'Placenta Encapsulations', 'Blow Dry/Out Services', 'Occupational Therapy', 'Gas Stations', 'Tax Services', 'Country Dance Halls', 'Botanical Gardens', 'Wine Tasting Room', 'Calabrian', 'Elementary Schools', 'Airport Terminals', 'Hazardous Waste Disposal', 'Electronics', 'Motorsport Vehicle Dealers', 'Hindu Temples', 'Sugaring', 'Argentine', 'Stonemasons', 'Mobile Home Dealers', 'Transportation', 'Pet Stores', 'Pest Control', 'Art Space Rentals', 'Damage Restoration', 'Hot Pot', 'Pet Cremation Services', 'Brewing Supplies', 'Mediterranean', 'Architects', 'Motorcycle Parts & Supplies', 'Dumplings', 'Art Galleries', 'Internal Medicine', 'Watch Repair', 'Diving', 'Hot Dogs', 'Pet Adoption', 'Southern', 'Video/Film Production', 'Pickleball', 'Dominican', 'Yelp Events', 'Mohels', 'Elder Law', 'Indian', 'Horse Equipment Shops', 'Senior Centers', 'Pet Transportation', 'Bakeries', 'Haunted Houses', 'Bookstores', 'Generator Instal

In [179]:
# drop unnecessary columns
df = df[['business_id', 'name', 'address', 'city', 'state', 'stars', 'review_count', 'is_open', 'attributes', 'categories']]

In [180]:
df['is_open'] = df['is_open'].astype(bool)

In [181]:
df['attributes'] = df['attributes'].apply(json.dumps)

print(df['attributes'])

0                             {"ByAppointmentOnly": "True"}
1                    {"BusinessAcceptsCreditCards": "True"}
2         {"BikeParking": "True", "BusinessAcceptsCredit...
3         {"RestaurantsDelivery": "False", "OutdoorSeati...
4         {"BusinessAcceptsCreditCards": "True", "Wheelc...
                                ...
150341    {"ByAppointmentOnly": "False", "RestaurantsPri...
150342    {"BusinessAcceptsCreditCards": "True", "Restau...
150343    {"RestaurantsPriceRange2": "1", "BusinessAccep...
150344    {"BusinessParking": "{'garage': False, 'street...
150345    {"WheelchairAccessible": "True", "BusinessAcce...
Name: attributes, Length: 150346, dtype: object

In [182]:
# filtering categories to ensure we are getting food or restaurant specific locations
df = df[df['categories'].str.contains(r'\b(Restaurants)\b', case=False, na=False)]

df = df.reset_index(drop=True)

df

/var/folders/nt/9lkpkjp92m11sfbsz_f__lch0000gn/T/ipykernel_51955/3016643974.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df = df[df['categories'].str.contains(r'\b(Restaurants)\b', case=False, na=False)]

,business_id,name,address,city,state,stars,review_count,is_open,attributes,categories
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,4.0,80,True,"{""RestaurantsDelivery"": ""False"", ""OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B..."
1,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,TN,2.0,6,True,"{""BusinessParking"": ""None"", ""BusinessAcceptsCr...","Burgers, Fast Food, Sandwiches, Food, Ice Crea..."
2,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,8025 Mackenzie Rd,Affton,MO,3.0,19,False,"{""Caters"": ""True"", ""Alcohol"": ""u'full_bar'"", ""...","Pubs, Restaurants, Italian, Bars, American (Tr..."
3,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,TN,1.5,10,True,"{""RestaurantsAttire"": ""'casual'"", ""Restaurants...","Ice Cream & Frozen Yogurt, Fast Food, Burgers,..."
4,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,NaN,Tampa Bay,FL,4.0,10,True,"{""Alcohol"": ""'none'"", ""OutdoorSeating"": ""None""...","Vietnamese, Food, Restaurants, Food Trucks"
...,...,...,...,...,...,...,...,...,...,...
52263,l9eLGG9ZKpLJzboZq-9LRQ,Wawa,19 N Bishop Ave,Clifton Heights,PA,3.0,11,True,"{""BikeParking"": ""True"", ""BusinessAcceptsCredit...","Restaurants, Sandwiches, Convenience Stores, C..."
52264,cM6V90ExQD6KMSU3rRB5ZA,Dutch Bros Coffee,1181 N Milwaukee St,Boise,ID,4.0,33,True,"{""WiFi"": ""'free'"", ""RestaurantsGoodForGroups"":...","Cafes, Juice Bars & Smoothies, Coffee & Tea, R..."
52265,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,1108 S 9th St,Philadelphia,PA,4.5,35,True,"{""WheelchairAccessible"": ""False"", ""Restaurants...","Restaurants, Mexican"
52266,2O2K6SXPWv56amqxCECd4w,The Plum Pit,4405 Pennell Rd,Aston,DE,4.5,14,True,"{""RestaurantsDelivery"": ""False"", ""BusinessAcce...","Restaurants, Comfort Food, Food, Food Trucks, ..."
52267,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,AB,4.5,18,False,"{""Ambience"": ""{'touristy': False, 'hipster': F...","Middle Eastern, Restaurants"

In [183]:
# downloading data
df.to_csv('cleaned_restaurant_data.csv', index=False)